# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  # Pods for MapApp

  target 'MapApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

   # pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  end

  target 'MapAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end

#target 'MapApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapApp-tvOS

  #target 'MapApp-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
#  end


