# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  # Pods for MapApp

  target 'MapApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'MapApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapApp-tvOS

  #target 'MapApp-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
#  end


